"""
Django settings for dapricot project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/
from dapricot.core.utils import SecretsCollectionObject

# SECURITY WARNING: keep the secret key used in production secret!

DJANGO_SECRETS = SecretsCollectionObject('DJANGO_SECRETS', BASE_DIR)

SECRET_KEY = DJANGO_SECRETS.get_secret_value('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',

    'dapricot.core',
    'dapricot.auth',
    'dapricot.blog',
    'dapricot.pages',
    'dapricot.media',
    'dapricot.integrations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_apricot.urls'
print()
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(os.path.dirname(BASE_DIR), 'dapricot', 'core', 'templates'),
            os.path.join(os.path.dirname(BASE_DIR), 'dapricot', 'pages', 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_apricot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
DATABASE_SECRETS = SecretsCollectionObject('DATABASE_SECRETS', BASE_DIR)
DATABASE_ROUTERS = ['dapricot.core.routers.SecretsHandlerRouter',]
MAIN_DATABASE = 'default'
DATABASES = {
    'default': {
        'ENGINE': DATABASE_SECRETS.get_secret_value('ENGINE_DEFAULT'),
        'NAME': os.path.join(BASE_DIR, 
                             DATABASE_SECRETS.get_secret_value('NAME_DEFAULT')),
    },
    'secrets_db': {
        'ENGINE': DATABASE_SECRETS.get_secret_value('ENGINE_SECRETS'),
        'NAME': os.path.join(BASE_DIR, 
                             DATABASE_SECRETS.get_secret_value('NAME_SECRETS')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
print(os.path.dirname(BASE_DIR))
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(os.path.dirname(BASE_DIR), 'dapricot', 'core', 'static'),
]
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'MEDIA')

SITE_ID = 1
AUTH_USER_MODEL = 'daauth.User'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_USER = 'admin@localhost'

USERNAME_FIELD = 'username'
